In [1]:
import numpy as np
a=np.array([1,3,5])
print(a)

[1 3 5]


In [43]:
import numpy as np
a=np.array([[1,3,5],[4,8,0]])
print(a)
w=np.argwhere(a==5)
print(w)



[[1 3 5]
 [4 8 0]]
[[0 2]]


In [ ]:
import numpy as np
a=np.array([[1,2,4,6],[5,8,3,9],[3,9,0,1]])
print(a)
print("\n")
b=np.array([[5,7,9,2],[6,8,7,5],[6,0,2,1]])
print(b)
c=a-b
print("\n",c)
add=a+b
print("\n",add)
m=a*b
print("\n",m)
d=1/a
print("\n",d)
dd=1/b
print("\n",dd)
s=a**2
print("\n",s)



import pandas as pd
data={ 'subject':['dbms','ds','es','psa'],'marks':[55,79,62,85]   
}
d=pd.DataFrame(data)
print(d)
d.set_index('subject',inplace=True)
print(d)




import pandas as pd
data = [
    ['dbms', 55],
    ['ds', 79],
    ['es', 62],
    ['psa', 85]
]

d = pd.DataFrame(data)
print(d)





import pandas as pd
data={ 'subject':['dbms','ds','es','psa'],'marks':[55,79,62,85]   
}
d=pd.DataFrame(data)
print(d)
e=(d['marks']/100)*10
k=d['marks']+e
d['marks']=k
print(d)
print("hight marks \n")
k=d.loc[d['marks'].idxmax(),['subject','marks']]
print(k)
print("\n  to display the Subjects with Marks Greater than 60 ")
h=d.loc[d['marks']>60,['subject','marks']]
print(h)




import numpy as np
a=np.arange(1,25)
re=a.reshape(2,3,4)
print(re)


import numpy as np
a=np.random.randint(1,100,size =(2,4))
print(a)




import pandas as pd
data = {
    'Date': ['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04', '2024-01-05', '2024-01-06'],
    'Product': ['A', 'B', 'A', 'C', 'B', 'C'],
    'Region': ['North', 'South', 'North', 'East', 'South', 'West'],
    'Amount': [500, 300, 450, 200, 350, 150]
}
df = pd.DataFrame(data)
print(df)
df=df.loc[(df["Region"]=='South') & (df['Amount']>200) ,['Date','Product','Region','Amount']]
print(df)
df=df.loc[(df["Product"]=='A') ,['Date','Product','Region','Amount']]
print(df)





import pandas as pd
data = {
    'Date': ['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04', '2024-01-05', '2024-01-06'],
    'Product': ['A', 'B', 'A', 'C', 'B', 'C'],
    'Region': ['North', 'South', 'North', 'East', 'South', 'West'],
    'Amount': [500, 300, 450, 200, 350, 150]
}

df = pd.DataFrame(data)
df.rename(columns={'Date': 'Sale Date', 'Product': 'Item', 'Region': 'Location', 'Amount': 'Sales Amount'}, inplace=True)
print(df)





import numpy as np
a=np.random.randint(1,10,size=(5,5))
print(a)
sums=np.sum(a==7)
print(sums)
av=np.mean(a,axis=1)
print(av)
p=np.argwhere(a<5)
print(p)
t=a.T
print(t)




import pandas as pd
data = {
    'Name': ['Alice', 'Bob', 'Alice', 'David', 'Bob', 'Eve'],
    'Age': [25, 30, 25, 40, 30, 22],
    'City': ['New York', 'Los Angeles', 'New York', 'Chicago', 'Los Angeles', 'Boston']
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)
df_no_duplicates_all = df.drop_duplicates()

print("\nDataFrame after removing duplicates based on all columns:")
print(df_no_duplicates_all)
df_no_duplicates_name = df.drop_duplicates(subset='Name', keep='first')
print("\nDataFrame after removing duplicates based on the 'Name' column (keeping first occurrence):")
print(df_no_duplicates_name)




import pandas as pd

S1 = pd.Series([39, 41, 42, 44], index=['A', 'B', 'C', 'D'])
S2 = pd.Series([10, 10, 10, 10], index=['A', 'B', 'C', 'D'])
df = pd.DataFrame({'S1': S1, 'S2': S2})
print("Combined DataFrame:\n", df)

common_indices = S1.index.intersection(S2.index)
common_values = pd.DataFrame({'S1': S1[common_indices], 'S2': S2[common_indices]})
print("\nCommon Indices and Corresponding Values:\n", common_values)

sum_values = S1 + S2
print("\nSum of Values for Each Index:\n", sum_values)
greater_indices = S1[S1 > S2].index
print("\nIndices Where S1 > S2:\n", greater_indices)







import pandas as pd

company = pd.Series([350, 200, 800, 150], index=['TCS', 'Reliance', 'L&T', 'Wipro'])
print("Companies with profits exceeding 250 Crores:")
print(company[company > 250])

highest_profit_company = company.idxmax()
print("\nCompany with the highest profit:")
print(highest_profit_company)

average_profit = company.mean()
print("\nAverage profit:", average_profit)
print("Companies with profits above average:")
print(company[company > average_profit])
company_renamed = company.rename("Loss")
print("\nRenamed Series:\n", company_renamed)






import pandas as pd
import numpy as np

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', np.nan],
    'Age': [25, np.nan, 35, 40, 29],
    'Salary': [50000, np.nan, 60000, 70000, np.nan],
    'Department': ['HR', 'IT', 'IT', np.nan, 'HR']
}
df = pd.DataFrame(data)
print("Original DataFrame:\n", df)
median_age = df['Age'].median()
df['Age'].fillna(median_age, inplace=True)
print("\nDataFrame after filling missing 'Age' with median:\n", df)
cleaned_df = df.dropna()
print("\nDataFrame after dropping rows with any missing values:\n", cleaned_df)
mode_department = df['Department'].mode()[0]
df['Department'].fillna(mode_department, inplace=True)
print("\nDataFrame after replacing missing 'Department' with mode:\n", df)







import numpy as np

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
horizontal_concat = np.hstack((array1, array2))
vertical_concat = np.vstack((array1, array2))

print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Horizontal Concatenation:\n", horizontal_concat)
print("Vertical Concatenation:\n", vertical_concat)










import import pandas as pd

data = {
    'Rollno': [1, 2, 3, 4, 5],
    'Name': ['Naveen', 'Mohit', 'Karthikeya', 'Markendya', 'Ranju'],
    'Age': [19, 18, 17, 17, 16],
    'Marks': [78, 67, 60, 80, 86]
}
df = pd.DataFrame(data)
marks_range = df['Marks'].max() - df['Marks'].min()
print("Range of Marks:", marks_range)

new_student = pd.DataFrame({'Rollno': [6], 'Name': ['Vijay'], 'Age': [19], 'Marks': [90]})
df = pd.concat([df, new_student], ignore_index=True)

mean_age = df['Age'].mean()
mode_age = df['Age'].value_counts().idxmax() 
print("Mean Age:", mean_age)
print("Mode Age:", mode_age)

row_count = len(df)
print("Number of Rows:", row_count)

print("\nUpdated DataFrame:\n", df)y as np
a=np.random.randint(1,100,size =(2,4))
print(a)








import matplotlib.pyplot as plt
scores = [55, 70, 75, 80, 85, 90, 95, 100, 60, 85, 78, 88, 92, 67, 77]

plt.figure(figsize=(12, 6))
plt.subplot(1, 2, 1)
plt.boxplot(scores)
plt.title('Box Plot of Exam Scores')
plt.xlabel('Scores')
plt.subplot(1, 2, 2)
plt.hist(scores, bins=8, color='skyblue', edgecolor='black')
plt.title('Histogram of Exam Scores')
plt.xlabel('Scores')
plt.ylabel('Frequency')
plt.tight_layout()
plt.show()




import matplotlib.pyplot as plt

study_hours = [1, 2, 3, 4, 5, 6, 7]
test_scores = [50, 55, 65, 70, 80, 85, 90]

plt.figure(figsize=(12, 6))
plt.subplot(1, 2, 1)
plt.scatter(study_hours, test_scores, color='blue', edgecolor='black')
plt.title('Scatter Plot: Study Hours vs Test Scores')
plt.xlabel('Study Hours')
plt.ylabel('Test Scores')

plt.subplot(1, 2, 2)
plt.plot(study_hours, test_scores, marker='o', color='green')
plt.title('Line Plot: Study Hours vs Test Scores')
plt.xlabel('Study Hours')
plt.ylabel('Test Scores')

plt.tight_layout()
plt.show()





import pandas as pd
import matplotlib.pyplot as plt

age_groups = ['18-25', '26-35', '36-45', '46-55', '56-65']
frequencies = [10, 15, 20, 5, 3]

data = {'Age Group': age_groups, 'Frequency': frequencies}
df = pd.DataFrame(data)

df['Cumulative Frequency'] = df['Frequency'].cumsum()

print(df)

plt.figure(figsize=(8, 6))
plt.pie(df['Frequency'], labels=df['Age Group'], autopct='%1.1f%%', startangle=90, colors=plt.cm.tab10.colors)
plt.title('Age Distribution')
plt.show()

In [151]:
import pandas as pd
import numpy as np

# Example data
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', np.nan],
    'Age': [25, np.nan, 35, 40, 29],
    'Salary': [50000, np.nan, 60000, 70000, np.nan],
    'Department': ['HR', 'IT', 'IT', np.nan, 'HR']
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

# Fill missing values in the 'Age' column with the median
median_age = 90000
df['Age'] = df['Age'].fillna(median_age)

print("\nUpdated DataFrame:")
print(df)


Original DataFrame:
      Name   Age   Salary Department
0    Alice  25.0  50000.0         HR
1      Bob   NaN      NaN         IT
2  Charlie  35.0  60000.0         IT
3    David  40.0  70000.0        NaN
4      NaN  29.0      NaN         HR

Updated DataFrame:
      Name      Age   Salary Department
0    Alice     25.0  50000.0         HR
1      Bob  90000.0      NaN         IT
2  Charlie     35.0  60000.0         IT
3    David     40.0  70000.0        NaN
4      NaN     29.0      NaN         HR


In [157]:
import pandas as pd
import numpy as np

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', np.nan],
    'Age': [25, np.nan, 35, 40, 29],
    'Salary': [50000, np.nan, 60000, 70000, np.nan],
    'Department': ['HR', 'IT', 'IT', np.nan, 'HR']
}
df = pd.DataFrame(data)
print("Original DataFrame:\n", df)
cleaned_df = df.dropna()
print("\nDataFrame after dropping rows with any missing values:\n", cleaned_df)




Original DataFrame:
       Name   Age   Salary Department
0    Alice  25.0  50000.0         HR
1      Bob   NaN      NaN         IT
2  Charlie  35.0  60000.0         IT
3    David  40.0  70000.0        NaN
4      NaN  29.0      NaN         HR

DataFrame after dropping rows with any missing values:
       Name   Age   Salary Department
0    Alice  25.0  50000.0         HR
2  Charlie  35.0  60000.0         IT


In [163]:
import pandas as pd
import numpy as np

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', np.nan],
    'Age': [25, np.nan, 35, 40, 29],
    'Salary': [50000, np.nan, 60000, 70000, np.nan],
    'Department': ['HR', 'IT', 'IT', np.nan, 'HR']
}
df = pd.DataFrame(data)
print("Original DataFrame:\n", df)
mode_department = df['Department'].mode()[0]
df['Department'].fillna(mode_department)
print("\nDataFrame after replacing missing 'Department' with mode:\n", df)



Original DataFrame:
       Name   Age   Salary Department
0    Alice  25.0  50000.0         HR
1      Bob   NaN      NaN         IT
2  Charlie  35.0  60000.0         IT
3    David  40.0  70000.0        NaN
4      NaN  29.0      NaN         HR

DataFrame after replacing missing 'Department' with mode:
       Name   Age   Salary Department
0    Alice  25.0  50000.0         HR
1      Bob   NaN      NaN         IT
2  Charlie  35.0  60000.0         IT
3    David  40.0  70000.0        NaN
4      NaN  29.0      NaN         HR


In [165]:

import pandas as pd
data = {
    'Name': ['Alice', 'Bob', 'Alice', 'David', 'Bob', 'Eve'],
    'Age': [25, 30, 25, 40, 30, 22],
    'City': ['New York', 'Los Angeles', 'New York', 'Chicago', 'Los Angeles', 'Boston']
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)
df_no_duplicates_all = df.drop_duplicates()

print("\nDataFrame after removing duplicates based on all columns:")
print(df_no_duplicates_all)
df_no_duplicates_name = df.drop_duplicates(subset='Name', keep='first')
print("\nDataFrame after removing duplicates based on the 'Name' column (keeping first occurrence):")
print(df_no_duplicates_name)


Original DataFrame:
    Name  Age         City
0  Alice   25     New York
1    Bob   30  Los Angeles
2  Alice   25     New York
3  David   40      Chicago
4    Bob   30  Los Angeles
5    Eve   22       Boston

DataFrame after removing duplicates based on all columns:
    Name  Age         City
0  Alice   25     New York
1    Bob   30  Los Angeles
3  David   40      Chicago
5    Eve   22       Boston

DataFrame after removing duplicates based on the 'Name' column (keeping first occurrence):
    Name  Age         City
0  Alice   25     New York
1    Bob   30  Los Angeles
3  David   40      Chicago
5    Eve   22       Boston


In [103]:
import numpy as np
a=np.array([[1,3,5],[4,8,0]])
b=np.array([[12,233,55],[45,58,6]])
h=np.vstack((a,b))
r=np.hstack((a,b))
print(h)




[[  1   3   5]
 [  4   8   0]
 [ 12 233  55]
 [ 45  58   6]]


In [73]:



import numpy as np
a=np.random.randint(500,550,size =(7,3))
print(a)

[[517 528 526]
 [501 520 547]
 [512 548 536]
 [506 536 547]
 [505 517 537]
 [543 523 502]
 [515 512 506]]


In [141]:
import pandas as pd

data = {
    'Rollno': [1, 2, 3, 4, 5],
    'Name': ['Naveen', 'Mohit', 'Karthikeya', 'Markendya', 'Ranju'],
    'Age': [19, 18, 17, 17, 16],
    'Marks': [78, 67, 60, 80, 86]
}

z = pd.DataFrame(data)
print("Original DataFrame:")
print(z)

# Update the name "Naveen" to "Priya"
z.loc[z['Name'] == 'Naveen', 'Name'] = 'Priya'

print("\nUpdated DataFrame:")
print(z)


Original DataFrame:
   Rollno        Name  Age  Marks
0       1      Naveen   19     78
1       2       Mohit   18     67
2       3  Karthikeya   17     60
3       4   Markendya   17     80
4       5       Ranju   16     86

Updated DataFrame:
   Rollno        Name  Age  Marks
0       1       Priya   19     78
1       2       Mohit   18     67
2       3  Karthikeya   17     60
3       4   Markendya   17     80
4       5       Ranju   16     86


In [139]:

import  pandas as pd

data = {
    'Rollno': [1, 2, 3, 4, 5],
    'Name': ['Naveen', 'Mohit', 'Karthikeya', 'Markendya', 'Ranju'],
    'Age': [19, 18, 17, 17, 16],
    'Marks': [78, 67, 60, 80, 86]
}
z=pd.DataFrame(data)
print(z)
daa = {
    'Rollno': [1, 2, 3, 4, 5],
    'Name': ['Naveen', 'Mohit', 'Karthikeya', 'Markendya', 'Ranju'],
    'Age': [19, 18, 17, 17, 16],
    'Marks': [78, 67, 60, 80, 86]
}
a=pd.DataFrame(daa)
h=pd.concat([z,a], ignore_index=True)
print(h)

   Rollno        Name  Age  Marks
0       1      Naveen   19     78
1       2       Mohit   18     67
2       3  Karthikeya   17     60
3       4   Markendya   17     80
4       5       Ranju   16     86
   Rollno        Name  Age  Marks
0       1      Naveen   19     78
1       2       Mohit   18     67
2       3  Karthikeya   17     60
3       4   Markendya   17     80
4       5       Ranju   16     86
5       1      Naveen   19     78
6       2       Mohit   18     67
7       3  Karthikeya   17     60
8       4   Markendya   17     80
9       5       Ranju   16     86


In [ ]:
import pandas as pd

# Create two Series
subjects = pd.Series(['MS', 'ES', 'FP'])
marks = pd.Series([67, 979, 99, 690])

# Print the subjects
print("Subjects:")
print(subjects)

# Print the marks
print("\nMarks:")
print(marks)

# Add 5 to all marks
marks += 5

# Print the updated marks
print("\nUpdated Marks (after adding 5):")
print(marks)


In [181]:
import pandas as pd
subjects =['S','f', 'ES', 'FP']
marks = [67, 979, 99, 690]
s= pd.Series(subjects,marks)

print(pd.Series(subjects,marks))


67      S
979     f
99     ES
690    FP
dtype: object
